"""empty message

Revision ID: 083b5f457145
Revises: a337de165509
Create Date: 2024-07-12 00:44:51.845316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '083b5f457145'
down_revision = 'a337de165509'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog_table', schema=None) as batch_op:
        batch_op.alter_column('spayed_neutered',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog_table', schema=None) as batch_op:
        batch_op.alter_column('spayed_neutered',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    # ### end Alembic commands ###
