"""empty message

Revision ID: 24166d2b31f0
Revises: 
Create Date: 2024-07-09 00:44:15.110263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24166d2b31f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('dog_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.Boolean(), nullable=False),
    sa.Column('breed', sa.String(length=250), nullable=False),
    sa.Column('spayed_neutered', sa.Boolean(), nullable=False),
    sa.Column('weight', sa.String(length=250), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorite_dog_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id_favorites', sa.Integer(), nullable=True),
    sa.Column('favorite_dog_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['favorite_dog_id'], ['dog_table.id'], ),
    sa.ForeignKeyConstraint(['user_id_favorites'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite_dog_table')
    op.drop_table('dog_table')
    op.drop_table('user_table')
    # ### end Alembic commands ###
