"""empty message

Revision ID: 5e4535b46b09
Revises: e4cc83a28528
Create Date: 2024-07-19 16:13:22.502208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e4535b46b09'
down_revision = 'e4cc83a28528'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog_table', schema=None) as batch_op:
        batch_op.alter_column('avatar',
               existing_type=sa.TEXT(),
               type_=sa.String(length=250),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog_table', schema=None) as batch_op:
        batch_op.alter_column('avatar',
               existing_type=sa.String(length=250),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
