"""empty message

Revision ID: a7a589acb7a0
Revises: 29fa80065e94
Create Date: 2024-07-02 02:49:07.753755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7a589acb7a0'
down_revision = '29fa80065e94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('dog_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.Boolean(), nullable=False),
    sa.Column('breed', sa.String(length=250), nullable=False),
    sa.Column('spayed_neutered', sa.Boolean(), nullable=False),
    sa.Column('weight', sa.String(length=250), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorite_dog_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id_favorites', sa.Integer(), nullable=True),
    sa.Column('favorite_dog_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['favorite_dog_id'], ['dog_table.id'], ),
    sa.ForeignKeyConstraint(['user_id_favorites'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key')
    )
    op.drop_table('favorite_dog_table')
    op.drop_table('dog_table')
    op.drop_table('user_table')
    # ### end Alembic commands ###
