"""empty message

Revision ID: ae13f6195abd
Revises: d5c8f68b2a6b
Create Date: 2024-07-17 16:03:19.536412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae13f6195abd'
down_revision = 'd5c8f68b2a6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog_table', schema=None) as batch_op:
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###
