"""empty message

Revision ID: d5c8f68b2a6b
Revises: ec3f6affa88c
Create Date: 2024-07-15 17:22:23.456141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5c8f68b2a6b'
down_revision = 'ec3f6affa88c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog_table', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
