"""empty message

Revision ID: e4cc83a28528
Revises: ae13f6195abd
Create Date: 2024-07-17 16:19:16.006396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4cc83a28528'
down_revision = 'ae13f6195abd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog_table', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=250), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
